[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
script = "script"
test = "test"

gas_reports = ["*"]

solc = "0.8.13"

optimizer = true
optimizer_runs = 200

initial_balance = '0xffffffffffffffffffffffff'
chain_id = 1

[fuzz]
runs = 1_000 

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${MAINNET_API_KEY}"
goerli = "https://eth-goerli.g.alchemy.com/v2/${GOERLI_API_KEY}"


[etherscan]
mainnet = { key = "${ETHERSCAN_DEFAULT_KEY}" }
goerli = { key = "${ETHERSCAN_DEFAULT_KEY}" }



# See more config options https://github.com/foundry-rs/foundry/tree/master/config